### ISSUE TITLE
Spidev error on first run

### ISSUE THREAD

**Issue by justcop** [KalebClark/InfoWindow#11]
I'm running this for the first time.
When running requirements.txt I get the error:

Could not find a version that satisfies the requirement spidev==3.3 (from -r requirements.txt (line 85)) (from versions: 2.0, 3.0, 3.1, 3.2, 3.4, 3.5)
No matching distribution found for spidev==3.3 (from -r requirements.txt (line 85))

This appears to be because there is no version 3.3 of spidev in pip and never has been.

Nevertheless as I have spidev 3.4 installed I suspected it might work just fine, however, I get the following error on running it:

Traceback (most recent call last):
  File "infowindow.py", line 8, in <module>
    from mod_infowindow import infowindow
  File "/home/pi/InfoWindow/mod_infowindow/infowindow.py", line 1, in <module>
    from driver import epd7in5b
  File "/home/pi/InfoWindow/driver/epd7in5b.py", line 27, in <module>
    import epdif
  File "/home/pi/InfoWindow/driver/epdif.py", line 38, in <module>
    SPI = spidev.SpiDev(0, 0)
IOError: [Errno 2] No such file or directory

I've also tried upgrading to spidev 3.5 but also not allowing me to run it.

**Comment by justcop** [comment]
Fixed by activating SPI by using the raspi-config tool under Interface Options
