### ISSUE TITLE
todoist

### ISSUE THREAD

**Issue by morningshane** [KalebClark/InfoWindow#8]
Traceback (most recent call last):
  File "infowindow.py", line 15, in <module>
    from mod_todo import mod_todoist as modTodo             # TODO
  File "/home/pi/InfoWindow/mod_todo/mod_todoist.py", line 1, in <module>
    import todoist
ImportError: No module named todoist

I have typed in my todoist API key but still showed this

**Comment by justcop** [comment]
Try  `pip install todoist-python`
in cli before running
worked for me
